###
GET http://localhost:3000/api/categories

###
GET http://localhost:3000/api/categories/4

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Laptop",
    "description": "All Laptops"
}

###
PATCH http://localhost:3000/api/categories/3
Content-Type: application/json

{
    "name": "Laptop",
    "description": "This Laptop Category"
}

###
DELETE http://localhost:3000/api/categories/5
