version: '3.9'
services:
  mysqlserver:
    image: mysql:8.0.30-debian
    container_name: mysqlserver
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs